version: "3.8"
services:

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "80:80"
    environment:
      NODE_ENV: dev

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    command: mongod --wiredTigerCacheSizeGB 2
    environment:
      TZ: "CET"
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"

  backend:
    image: do1phin/city-ops:latest
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:secret@mongo:27017/cityOps?authSource=admin